services:
  - name: jobboard
    type: web
    env: docker
    plan: starter
    region: oregon
    dockerfilePath: Dockerfile
    buildCommand: ""
    startCommand: ""
    envVars:
      - key: SECRET_KEY
        sync: false
      - key: DATABASE_URL
        sync: false
