# Generated by Django 5.0.4 on 2024-04-26 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_board', '0002_remove_applicant_status_remove_company_company_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant',
            name='email',
        ),
        migrations.RemoveField(
            model_name='company',
            name='email',
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_company',
            field=models.BooleanField(default=False),
        ),
    ]
