# Generated by Django 5.0.4 on 2024-04-27 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_board', '0003_remove_applicant_email_remove_company_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='cover_letter',
            field=models.FileField(default=None, upload_to='cover_letters/'),
            preserve_default=False,
        ),
    ]
