# Generated by Django 5.0.4 on 2024-04-27 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_board', '0004_application_cover_letter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='cover_letter',
            field=models.FileField(default='No cover letter provided', upload_to='cover_letters/'),
        ),
    ]
