# Generated by Django 5.0.4 on 2024-04-27 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_board', '0005_alter_applicant_cover_letter'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='application',
            unique_together={('applicant', 'job_posting')},
        ),
    ]
